Mika Sah – The Dualblade ThunderSky Rider
Mika Sah, cascading fiery crimson hair layered and practical swept back in messy combat-ready half-up ponytail with rest flowing behind like banner of flame shimmering with hints of gold and bronze, large almond-shaped deep lightning-yellow eyes shifting between warm amber and blazing electric fire framed by thick crimson lashes, soft oval face with delicate jawline tapering to gentle point, small straight nose, full crimson lips curved in fierce knowing smile, fair luminous cream-colored skin with faint golden undertone, classic hourglass figure with slender waist flaring into full rounded hips, thick powerful smooth thighs, massive full G-cup bust straining against minimal armor, bare shoulders with long graceful arms and delicate hands, furred brown long coat open revealing minimal bra-like bronze-and-gold breastplate leaving cleavage bare and taut stomach exposed, armored dark red leather mini skirt slit high on sides revealing full length of thick smooth bare thighs, spiked bronze-and-gold shoulder armor with spikes curving upward like thunder god horns, bronze-and-gold bracelet on wrist sparkling with captured lightning, two big-sized bronze-and-gold mechanical containers on each hip as grappling hook gears, silver short armor boots with sharp heels crackling with lightning energy when landing, no thigh coverings. Her weapons are dual blades (Fanananana) each a short sword of bronze and gold with edge crackling with lightning-yellow thunder aura, plus steel cables from hip containers for aerial swinging, accompanied by Pere Pere the lightning falcon with dark bronze to bright gold gradient feathers and lightning-yellow eyes.

Fanny
Fanny, voluminous midnight black hair with emerald-green highlights in trendy layered choppy wolf cut, top sections pulled into high spiky ponytail flaring upward like flame with jagged piecey bangs framing face, sharp piercing emerald-amber green large almond-shaped eyes with heavy smoky green-gold eyeshadow and thick winged eyeliner, thick sharply angled black eyebrows with vivid green highlights, sharp angular jawline and high sculpted cheekbones, straight narrow nose, full glossy bold orange-red lips, porcelain jade skin with pearlescent jade-toned highlighter, distinctive mole above left eyebrow, off-shoulder white ribbed crop top with bold crimson-red Japanese calligraphy "FANNY" across front, oversized shearling fur jacket with thick cream-colored collar and sleek black leather body sleeves rolled to forearms, black mini shorts with distressed hem, black mesh fishnet leggings climbing up thick powerful thighs, slim black belt with silver buckle connecting to hip gear mechanisms, signature purple-reinforced gauntlets with silver plating and gold accents on forearms, silver chain necklaces and single hoop earring in left ear, emerald-green painted nails chipped, two heavy iron-like hip gear mechanisms on each side housing steel cables, chunky black leather loafer boots with platformed thick soles and silver buckles. Her weapons are twin long silver blades with emerald-green gem crossguards, plus steel cables from hip gear for aerial mobility.

Marianzo Sah – The Storm Instructor
Marianzo Sah, thick mane of deep auburn hair shoulder-length often tied back in loose tail with hints of silver at temples, deep burning amber-yellow eyes like lightning captured in amber with crow's feet at corners, strong square jawline with full thick auburn beard coarse and well-groomed slightly unkempt, prominent slightly crooked nose, weathered rugged fair skin with faint golden undertone and jagged scar from left eyebrow to temple, massive bulky powerfully built frame well over six feet with impossibly broad shoulders, thick ropey arms with bulging biceps, broad solid chest wall of muscle tapering to narrow waist, thick sturdy legs like ancient oaks, thick fur-lined brown thunder beast hide jacket open revealing massive chest beneath, simple black tactical vest with chest bare beneath, heavy plate bronze-and-dark iron shoulder armor with outward-curving spikes, dark cargo pants tucked into heavy black leather steel-toed boots with thick grippled soles, thick dark leather belt with heavy mechanical containers on each hip for grappling cables, heavy leather bracers reinforced with bronze on wrists, thick chain necklace with bronze thunderbird amulet, massive calloused hands with thick steady fingers. His weapon is Stormbreaker thunder hammer, a massive hammer with one side curved dark bronze blade crackling with lightning and other side flat devastating hammer head, handle wrapped in thick leather with thunderbird-head pommel, plus heavy bronze-threaded grappling cables, riding TenTen the massive thunder eagle.

Selviath Sah – The Sky Dancer
Selviath Sah, flowing pale gold blonde hair in soft waves past shoulders shimmering with silver and white often worn loose or in elegant ponytail, large almond-shaped pale blue-white eyes like lightning in ice, soft oval face with high gentle cheekbones and small pointed chin, delicate slightly upturned nose, full naturally pink lips curved in gentle smile, pale almost translucent luminous skin with faint golden undertone and small lightning-shaped Mankah symbols on shoulders and wrists, perfect hourglass figure with slender impossibly thin waist flaring into full rounded hips, thick smooth powerful thighs, full prominent chest, flowing off-shoulder sheer white top with delicate gold lightning-and-cloud embroidery, flowing layered white and pale blue mini skirt held by thin gold thunderbird buckle, no leggings with bare thighs, flowing sheer white cape attached at shoulders embroidered with gold Mankah patterns, gold bracelets with pale blue gems on wrists, gold lightning-bolt pendant necklace, delicate gold feather earrings, elegant gold sandals with straps climbing calves and delicate heels. Her weapons are Cloudcutters, a pair of elegant thin curved white gold daggers with edges lined with tiny lightning-charged crystals, hilts wrapped in pale blue leather with wing-shaped crossguards, plus small gold-and-white grappling gear with near-invisible cables, riding Lumina the snow-white storm hawk.

Keirashkan Zein – The Demon Lord of the Sundering
Keirashkan Zein, cascading absolute black hair in thick waves past shoulders moving as if alive with two pairs of small curved obsidian horns above ears, pools of absolute darkness for eyes with glowing red ember pupils, perfectly symmetrical heartbreakingly beautiful face with strong jaw, high sharp cheekbones, straight elegant nose, full red lips curved in smug knowing smirk, flawless pale moonlight skin with faint dark vein network and dark sigils glowing with inner fire on forehead neck and arms, towering twenty-foot frame with massive yet perfectly proportioned build, broad shoulders, thick corded arms, fortress-like chest, pillar-like legs, massive devastating beautiful wings spanning over a hundred feet with dark bone skeleton and dark iridescent membranes edged jagged with blazing red fire veins, flowing black open coat revealing bare chest beneath trimmed with dark fur at collar, tight black pants tucked into black leather-and-bone heeled boots, cloak of shadow darkness given form hanging from shoulders, black iron necklace with shattered sun pendant, black long sharp fingernails, natural crown of black bone on head. His weapons are his own body, claws, wings, and demonic magic, no external forged weapons.

Brunhilde Stormforger – The Abyssal Smith
Brunhilde Stormforger, dark auburn hair cropped short almost shaved on sides with thick crest on top standing like frozen flame with gray lightning-bolt streaks, deep burning amber-orange eyes glowing faintly like magma, square strong face with broad jaw and broken nose, thick steel-wool gray beard braided with copper and gold wires with single thin chin braid ending in small ring, dark deep bronze almost black skin marked with thin white scars and jagged gash on left cheek, compact but immense five-foot frame with broad shoulders, thick corded arms, massive calloused hands with fused misshapen fingers, thick thunder beast hide apron reinforced with dark iron rune plates over black heat-resistant tunic with sleeves rolled to elbows, thick dark leather belt studded with small tools, heavy black iron boots with steel caps. Her weapon is a massive two-handed hammer with dark iron thunderbolt-shaped head, dragon-leather wrapped handle, pommel set with frozen lightning gemstone.

Lumina – The Snow Storm Hawk
Lumina, pure white feathers with pale blue tips like winter twilight, impossibly soft and translucent shimmering with inner glow, wings broad and sweeping fifteen feet from tip to tip with silent flight, large almond-shaped pale blue-white eyes glowing faintly with cold intelligence, curved pale gold beak, sharp smaller deadly talons, faint frost emanating from feathers crystallizing air, trailing glittering frost in flight, soft mournful cooing sound like wind through winter branches. No weapons aside from natural beak and talons, abilities include frost trail, silent storm, winter's embrace, ice dive.

Pere Pere – The Lightning Falcon
Pere Pere, dark bronze to bright gold gradient feathers sleek and metallic crackling with static electricity, wingspan over ten feet broad and powerful with humming crackling sound, two points of lightning-yellow large round predator's eyes glowing with inner fire, curved dark iron beak, massive talons each size of man's hand curved like hooks black tinged with gold sparking with electricity, feathers ruffle when angry smooth when calm, trails of electricity when flying, thunderous scream. No external weapons, abilities include lightning dive, storm scout, electric wings, falcon's fury, telepathic bond with Mika.

Toren Embervein – The Ember Sage
Toren Embervein, wild tangle of dark brown curls standing in every direction streaked with gray and static sparks, bright eager eyes constantly searching, gentle rounded face with high cheeks that flush when excited, small crooked nose, thin expressive lips curved in distracted smile, lean wiry almost frail five-foot frame slightly stooped, thin arms with delicate precise hands covered in dozens of overlapping burn scars with misshapen fused fingers, faint smell of ozone and burning wood, leather apron thick and scarred over simple brown tunic with apron covered in dozens of tool pockets, no armor or weapons, tools like pliers and wrenches as implements.

Iridis – The Blind Oracle
Iridis, thin wispy bone-white hair in simple braid to waist, clouded white unseeing eyes with vast depth, wrinkled face with deep lines carved by centuries, prominent cheekbones, sharp jaw, thin lips curved in knowing smile, tiny frail five-foot frame with papery translucent skin, simple flowing white layered robes worn until transparent, white fur cloak soft as clouds draped over shoulders, barefoot calloused feet. No weapons, only prophetic abilities.

The Thunderer – The First Storm
The Thunderer, no fixed form appears as massive warrior with dark bronze almost black skin crackling with electricity, blazing gold eyes burning with fire of creation, wild unbound hair crackling with lightning moving without wind, strong angular primal face with powerful jaw and high cheekbones and straight strong nose, no beard, storm wings made of lightning and cloud spanning hundreds of feet not physical but metaphysical, no armor needed, body as armor, lightning as weapon, carries spark of divine lightning.

TenTen – The Thunderlord's Wing
TenTen, enormous twenty-foot wingspan, dark bronze almost black feathers with burning amber tips crackling with stored lightning, blazing amber glowing eyes with inner fire, curved dark iron beak, talons size of man's hand curved black crackling with electricity, massive powerful body size of small aircraft. Abilities include lightning call, thunder scream, gust of war. No external weapons.

Priest Aldric Vane – The Light's Architect
Priest Aldric Vane, thin silken white hair past shoulders catching light and glowing faintly always perfectly maintained, pale blue-white winter-sky eyes calm cold penetrating lacking warmth, sharp angular gaunt face with high prominent cheekbones casting shadows, strong but not harsh jaw set in quiet resolve, straight aquiline nose, pale thin beard neatly trimmed bone white framing rarely-smiling mouth, pale almost translucent skin with faint luminescence and pale blue veins at temples and wrists, tall lean angular six-foot frame with slender build but iron beneath robes, long-fingered pale delicate hands always in motion leaving traces of light, flowing white robe of divine silk woven with starlight falling to ankles with wide flowing excessively long sleeves, Breastplate of Judgment silver-and-white crystalline substance bearing sun-and-stars symbol, pure white fur cloak draped over shoulders, bare feet, thin silver circlet on brow etched with purification runes glowing when channeling power, Scepter of Dawn white wood rod topped with captured sunlight crystal, sunburst pendant on silver chain. His weapon is the Scepter of Dawn as symbol, his abilities are channeling divine light for healing, blinding, trapping in light jails.